### ISSUE TITLE
Not sure plugins should be installed in /usr/lib/docker/

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/rhel-push-plugin#3]
Since this is a regular daemon service maybe it should be in /usr/sbin.

In order to get oci plugins through review, we were forced to move them to /usr/libexec/oci/hooks.d

**Comment by runcom** [comment]
We can handle this, the only plugin already shipped in rawhide and f24 is the novolume plugin - I can fix the spec file and install into /usr/sbin easily - I just want to have a standard and known way where we install plugins.
I also think that since the plugins are only meant to be used by the docker daemon the can also leave under /usr/libexec/docker

**Comment by rhatdan** [comment]
Lets throw them under /usr/libexec/docker, but this should be configurable in case some other distribution wants to use your plugins.

**Comment by runcom** [comment]
it will work everywhere as long as those folders are in $PATH - is /usr/libexec in path?

**Comment by runcom** [comment]
can we standardize this and always execute plugins found in /usr/libexec/docker?

**Comment by rhatdan** [comment]
Yes.  That works for me. and for Fedora Guidelines.

**Comment by runcom** [comment]
actually, /usr/sbin may be better cause those plugin are meant to be launched directly also.

**Comment by rhatdan** [comment]
Lets stick with /usr/libexec/docker/

**Comment by runcom** [comment]
fixed and tested in master
